# See: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      shell: bash
      run: |
        scripts/install-poetry.sh 1.5.1

    - name: Environment
      run: env | sort

    - name: Install dependencies
      run: make --assume-old=poetry.lock venv

    - name: Lint
      run: make check

    - name: Test
      run: make test
